<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29564" started-at="2016-11-07T07:43:56Z" finished-at="2016-11-07T07:44:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29564" started-at="2016-11-07T07:43:56Z" finished-at="2016-11-07T07:44:26Z">
      <class name="com.epam.scenarios.Craftsvilla">
        <test-method status="FAIL" signature="CartList()[pri:0, instance:com.epam.scenarios.Craftsvilla@25b2fe]" name="CartList" duration-ms="29554" started-at="2016-11-07T13:13:56Z" finished-at="2016-11-07T13:14:26Z">
          <exception class="com.epam.utils.CustomeExceptionUtil">
            <message>
              <![CDATA[Added to cart success Message is not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.epam.utils.CustomeExceptionUtil: Added to cart success Message is not found
	at com.epam.pageobjects.Craftsvilla_ProductDetails.addProductsToCart(Craftsvilla_ProductDetails.java:79)
	at com.epam.scenarios.Craftsvilla.CartList(Craftsvilla.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- com.epam.utils.CustomeExceptionUtil -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CartList -->
      </class> <!-- com.epam.scenarios.Craftsvilla -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
